# Generated by Django 4.2.23 on 2025-07-27 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='short_link',
        ),
    ]
