
INGREDIENT_NAME_LENGTH = 128
INGREDIENT_MEASUREMENT_UNIT_LENGTH = 64
RECIPE_NAME_LENGTH = 256
TAG_NAME_LENGTH = 32
TAG_SLUG_LENGTH = 32
USER_EMAIL_LENGTH = 254
USER_FIRST_NAME_LENGTH = 150
USER_LAST_NAME_LENGTH = 150
USER_USERNAME_LENGTH = 150

RECIPE_MIN_COOKING_TIME = 1  # in minutes
INGREDIENT_MIN_AMOUNT = 1  # minimum amount of ingredient in a recipe
